CREATE TABLE EMPT(EMPID NUMBER(4),FULLNAME VARCHAR2(20),DATEOFJOIN DATE,CITY VARCHAR2(20));

CREATE TABLE EMPT2(EMPID NUMBER(4),FULLNAME VARCHAR2(20),
MGRID NUMBER(4),DATEOFJOIN DATE,CITY VARCHAR2(20));

INSERT INTO EMPT2 VALUES(421,'RANA  ',876,'27-NOV-2015','NEW');

SELECT * FROM EMPT2

SELECT SUBSTR(FULLNAME,1,1) FROM EMPT2;

SELECT SUBSTR(FULLNAME,1,INSTR(FULLNAME,' ')) FROM EMPT2


CREATE TABLE ESALARY
(EMPID NUMBER(3),PROJECT CHAR(2),SALARY NUMBER(9,2),VARIABLE NUMBER(8,0));

INSERT INTO ESALARY VALUES(421,'P1',12000,0);

SELECT * FROM ESALARY
SELECT * FROM EE1



SELECT * FROM EE1 E, EE2 F
WHERE E.EMPID =F.EMPID FETCH FIRST 2 ROWS ONLY;

SELECT ENO,COUNT(*) FROM EMPLOY GROUP BY ENO HAVING 
COUNT(*)>1




SELECT * from EE1 E,EE2 F WHERE
E.EMPID =F.EMPID;
SELECT * FROM EMPT2
SELECT FULLNAME FROM EMPT2
WHERE EMPID IN 

SELECT EMPID,FULLNAME FROM EMPT2
WHERE EMPID IN






SELECT EMPID,FULLNAME FROM EMPT2 WHERE EMPID IN
(SELECT SUM(SALARY+VARIABLE)OVER()(PARTITION BY EMPID ORDER BY SALARY)R
FROM ESALARY);


SELECT EMPID,FULLNAME FROM EMPT2 WHERE EMPID IN




SELECT * FROM EMPT2 E1 
FULL OUTER JOIN ESALARY E2
ON E1.EMPID =E2.EMPID;


SELECT * FROM EMPT2 T1, ESALARY T2
WHERE T1.EMPID =T2.EMPID AND T2.PROJECT!='P1';


SELECT * FROM EMPT2 T1, ESALARY T2
WHERE T1.EMPID =T2.EMPID AND T1.CITY='MUMBAI' OR T1.MGRID='986';


SELECT * FROM EMPT2 WHERE CITY='MUMBAI' OR  MGRID='986';


SELECT * FROM
(SELECT MAX(SALARY)FROM EMPLOY3 ORDER BY SALARY DESC) WHERE ROWNUM <3


SELECT * FROM (SELECT ENAME,DEPTNO,SALARY,ROW_NUMBER()
OVER(PARTITION BY DEPTNO ORDER BY SALARY DESC)R
FROM EMPLOY3) WHERE R<3 ;


SELECT MAX(SALARY) FROM EMPLOY3 WHERE SALARY >
(SELECT MAX(SALARY) FROM EMPLOY3 )




 SELECT MIN(SALARY) FROM
 (SELECT DISTINCT SALARY FROM EMPLOY3 ORDER BY SALARY ASC) WHERE ROWNUM<3
 
 SELECT MAX(SALARY) FROM
 (SELECT DISTINCT SALARY FROM EMPLOY3 ORDER BY SALARY ASC) WHERE ROWNUM<=2





 
 
DELETE FROM EMPLOY WHERE ROWID NOT IN
(SELECT MIN(ROWID) FROM EMPLOY GROUP BY ENO)

































CREATE TABLE SALES1 
(SAL_ID NUMBER(5),NAME VARCHAR2(20),CITY VARCHAR2(20),COMM NUMBER(5,2));

INSERT INTO SALES1 VALUES(5006,'pual_adam','rome',0.13);


select * from sales1

select * from sales1 where city='paris' or city='rome'



CREATE STUDENT1234 SELECT * from STUDENT12 where 1=2;




SELECT * FROM (SELECT ENAME,DEPTNO,SALARY,ROW_NUMBER()
OVER(PARTITION BY DEPTNO ORDER BY SALARY DESC)R
FROM EMPLOY3) WHERE R<2;








SELECT * FROM(SELECT ENAME,SALARY,ROW_NUMBER()OVER(ORDER BY SALARY DESC)R
FROM EMPLOY3) WHERE R=3

SELECT 


SELECT MAX(MARKS) AS MARKS FROM STUDENT12
UNION ALL
SELECT MIN(MARKS)AS MARKS FROM STUDENT12



SELECT MAX(MARKS),MIN(MARKS) FROM STUDENT12


SELECT * FROM PRO

SELECT NAME || '(' || SUBSTR(PROFESSION,1,1)||')' FROM PRO

