
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-31T21:14:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad2c9b8826c75939608f5561a2a0ad33b9dafaf9",
 "version": "2022.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
